# Generated by Django 2.2.12 on 2022-10-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='secondadress',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
