# Generated by Django 2.2.12 on 2022-10-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderplaced_secondadress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='secondadress',
        ),
    ]
